image:
  repository: image-registry.openshift-image-registry.svc:5000/helm-devel/catalog-app
  tag: latest

labels:
  stage: devel

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 250m
    memory: 512Mi

route:
  tls:
    enabled: false
