apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: maven-build-eventlistener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-push-trigger
      bindings:
        - ref: maven-build-triggerbinding
      template:
        ref: maven-build-triggertemplate
