apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    stage: {{ .Values.label.stage }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: {{ .Values.service.port }}
{{- if .Values.route.tls.enabled }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
