apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: maven-build-pipeline
spec:
  params:
    - name: maven_repo
      type: string
      description: "Maven repository/mirror URL to use for the build"
    - name: image_name
      type: string
      description: "Name of the image to build and push"
    - name: git_url
      type: string
      default: "https://github.com/ansibleking/ex288-practice.git"
    - name: git_revision
      type: string
      default: "main"
    - name: context_dir
      type: string
      default: "exam8-sim/maven-app"
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
        kind: Task
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git_url)
        - name: revision
          value: $(params.git_revision)

    - name: maven-build
      runAfter: ["fetch-source"]
      taskRef:
        name: maven
        kind: Task
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: GOALS
          value:
            - "-f"
            - "$(params.context_dir)/pom.xml"
            - "-DskipTests"
            - "clean"
            - "package"
        - name: MAVEN_MIRROR_URL
          value: $(params.maven_repo)
        - name: MAVEN_IMAGE
          value: "docker.io/library/maven:3.8-openjdk-11"
